package add_data;


import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lakshitha
 */
public class getd extends javax.swing.JFrame {

    /**
     * Creates new form getd
     */
    public getd() {
        initComponents();
        rootPane.setDefaultButton(jButton1);
    }
    
 
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Offline Translator");

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTextField1PropertyChange(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("Convert");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextPane1.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        jScrollPane1.setViewportView(jTextPane1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Enter Text Here :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Converted Text:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(326, 336));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
   
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    try {
            Connection con = DB.createConnection();
            
            String sentence=jTextField1.getText();
            jTextPane1.setText("");
            
            boolean dot=false;
            boolean exist=false;
            boolean exist2=false;
            
            String words[] =sentence.split(" ");
            int size =words.length;
            String word2=null;
            
            
            for(int i=0;i<size;i++){
                if(words[i].contains(".")){
                    dot=true;
                    words[i]=words[i].substring(0,words[i].length()-1);
                }
                ResultSet r1 = con.createStatement().executeQuery("select * from nouns where english='"+words[i]+"'");
                ResultSet r2 = con.createStatement().executeQuery("select * from s_verb where english='"+words[i]+"'");
                ResultSet r3 = con.createStatement().executeQuery("select * from no_meaning where english='"+words[i]+"'");
                ResultSet r8 = con.createStatement().executeQuery("select * from verbs_past where english='"+words[i]+"'");
                
                if(r1.next()){
                    exist2=true;
                    String in=r1.getString("sinhala");
                    if(dot==true){
                        String list=jTextPane1.getText();
                        jTextPane1.setText(list+" "+in+".");
                    }else{
                        String list=jTextPane1.getText();
                        jTextPane1.setText(list+" "+in+" ");
                    }
                }else if(r3.next()){
                    exist2=true;
                    String ineng=r3.getString("english");
                    String tense=r3.getString("nature");
                    
                    if(words[i].equals("am") || words[i].equals("is") || words[i].equals("are")){
                        ResultSet r4 = con.createStatement().executeQuery("select * from verbs_pre where english='"+words[i+1]+"'");
                        if(r4.next()){
                            String in2=r4.getString("sinhala");
                            if(dot==true){
                                String list=jTextPane1.getText();
                                jTextPane1.setText(list+" "+in2+".");
                            }else{
                                String list=jTextPane1.getText();
                                jTextPane1.setText(list+" "+in2+" ");
                            }
                        }
                    }else if(words[i].equals("will") ){
                        ResultSet r5 = con.createStatement().executeQuery("select * from verbs_fut where english='"+words[i+1]+"'");
                        if(r5.next()){
                            exist=true;
                            String in2=r5.getString("sinhala");
                            if(dot==true){
                                String list=jTextPane1.getText();
                                jTextPane1.setText(list+" "+in2+".");
                            }else{
                                String list=jTextPane1.getText();
                                jTextPane1.setText(list+" "+in2+" ");
                            }
                        }
                    }
                    else if(words[i].equals("can") ){
                        ResultSet r6 = con.createStatement().executeQuery("select * from s_can where english='"+words[i+1]+"'");
                        ResultSet r7 = con.createStatement().executeQuery("select * from edit where name='"+words[i-1]+"'");
                        if(r6.next()){
                            exist=true;
                            String in2=r6.getString("sinhala");
                            if(dot==true){
                                String list=jTextPane1.getText();
                                if(r7.next()){
                                    list=r7.getString("name2");
                                }
                                jTextPane1.setText(list+" "+in2+".");
                            }else{
                                String list=jTextPane1.getText();
                                if(r7.next()){
                                    list=r7.getString("name2");
                                };
                                jTextPane1.setText(list+" "+in2+" ");
                            }
                        }
                    }
                }else if(r2.next()){
                    exist2=true;
                    String in=r2.getString("sinhala");
                    if(!exist){
                        if(dot==true){
                            String list=jTextPane1.getText();
                            jTextPane1.setText(list+" "+in+".");
                        }else{
                            String list=jTextPane1.getText();
                            jTextPane1.setText(list+" "+in+" ");
                        }
                    }
                    
                }else if(r8.next()){
                    exist2=true;
                    exist=true;
                    String in2=r8.getString("future");
                    if(words.length>2){
                        String list=jTextPane1.getText();
                        String br[]=list.split("  ");
                        int s=br.length;
                        jTextPane1.setText(br[0]+" "+in2+" "+br[s-1]);
                    }else{
                        if(dot==true){
                        String list=jTextPane1.getText();
                        jTextPane1.setText(list+" "+in2+".");
                    }else{
                        String list=jTextPane1.getText();
                        jTextPane1.setText(list+" "+in2+" ");
                    }
                    }
                }
                
                
            }
            if(!exist2){
                JOptionPane.showMessageDialog(null, "Database Does not have entered data");
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        jTextField1.setText("");    
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1KeyTyped

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        try {
            Connection con = DB.createConnection();
            
            String sentence=jTextField1.getText();
            jTextPane1.setText("");
            
            boolean dot=false;
            boolean exist=false;
            boolean exist2=false;
            
            String words[] =sentence.split(" ");
            int size =words.length;
            String word2=null;
            
            for(int i=0;i<size;i++){
                if(words[i].contains(".")){
                    dot=true;
                    words[i]=words[i].substring(0,words[i].length()-1);
                }
                ResultSet r1 = con.createStatement().executeQuery("select * from nouns where english='"+words[i]+"'");
                ResultSet r2 = con.createStatement().executeQuery("select * from s_verb where english='"+words[i]+"'");
                ResultSet r3 = con.createStatement().executeQuery("select * from no_meaning where english='"+words[i]+"'");
                ResultSet r8 = con.createStatement().executeQuery("select * from verbs_past where english='"+words[i]+"'");
                
                if(r1.next()){
                    exist2=true;
                    String in=r1.getString("sinhala");
                    if(!exist){
                        if(dot==true){
                        String list=jTextPane1.getText();
                        jTextPane1.setText(list+" "+in+".");
                        }else{
                        String list=jTextPane1.getText();
                        jTextPane1.setText(list+" "+in+" ");
                        }
                    }
                    
                    
                }else if(r3.next()){
                    exist2=true;
                    String ineng=r3.getString("english");
                    String tense=r3.getString("nature");
                    
                    if(words[i].equals("am") || words[i].equals("is") || words[i].equals("are")){
                        ResultSet r4 = con.createStatement().executeQuery("select * from verbs_pre where english='"+words[i+1]+"'");
                        if(r4.next()){
                            String in2=r4.getString("sinhala");
                            if(dot==true){
                                String list=jTextPane1.getText();
                                jTextPane1.setText(list+" "+in2+".");
                            }else{
                                String list=jTextPane1.getText();
                                jTextPane1.setText(list+" "+in2+" ");
                            }
                        }
                    }else if(words[i].equals("will") ){
                        ResultSet r5 = con.createStatement().executeQuery("select * from verbs_fut where english='"+words[i+1]+"'");
                        if(r5.next()){
                            exist=true;
                            String in2=r5.getString("sinhala");
                            if(dot==true){
                                String list=jTextPane1.getText();
                                jTextPane1.setText(list+" "+in2+".");
                            }else{
                                String list=jTextPane1.getText();
                                jTextPane1.setText(list+" "+in2+" ");
                            }
                        }
                    }
                    else if(words[i].equals("can") ){
                        ResultSet r6 = con.createStatement().executeQuery("select * from s_can where english='"+words[i+1]+"'");
                        ResultSet r7 = con.createStatement().executeQuery("select * from edit where name='"+words[i-1]+"'");
                        if(r6.next()){
                            exist=true;
                            String in2=r6.getString("sinhala");
                            if(dot==true){
                                String list=jTextPane1.getText();
                                if(r7.next()){
                                    list=r7.getString("name2");
                                }
                                jTextPane1.setText(list+" "+in2+".");
                            }else{
                                String list=jTextPane1.getText();
                                if(r7.next()){
                                    list=r7.getString("name2");
                                };
                                jTextPane1.setText(list+" "+in2+" ");
                            }
                        }
                    }
                }else if(r2.next()){
                    exist2=true;
                    String in=r2.getString("sinhala");
                    if(!exist2){
                        if(dot==true){
                            String list=jTextPane1.getText();
                            jTextPane1.setText(list+" "+in+".");
                        }else{
                            String list=jTextPane1.getText();
                            jTextPane1.setText(list+" "+in+" ");
                        }
                    }
                    
                }else if(r8.next()){
                    exist2=true;
                    if(!exist){
                        String in2=r8.getString("future");
                        if(dot==true){
                        String list=jTextPane1.getText();
                        jTextPane1.setText(list+" "+in2+".");
                    }else{
                        String list=jTextPane1.getText();
                        jTextPane1.setText(list+" "+in2+" ");
                    }
                    }
                    
                }
                 
            }
            if(!exist2){
                JOptionPane.showMessageDialog(null, "Database Does not have entered data");
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        jTextField1.setText("");    
        
// TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTextField1PropertyChange
              
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1PropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(getd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(getd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(getd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(getd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new getd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables

    private int size(String[] words) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
